package com.symlab.hydra.network;

public enum Msg {
	REG_VM, INIT_OFFLOAD, APK_REQUEST, APK_SEND, READY, SUPPORT_OFFLOAD, EXECUTE, RESULT,

	REQUEST_STATUS, RESPONSE_STATUS,

	BLUETOOTH_PROFILER,

	REGISTER, REGISTERED, OFFLOAD, UNREGISTER, UNREGISTERED, DEVICE_LIST, FREE, CTRL_VM, 
	
	CLOUD, SMARTPHONE, LOCAL, GREEDY,

	PING, PONG,

	NONE, FINISH,
}
