package com.symlab.hydracloud;

public enum Msg2 {
	REG_VM, INIT_OFFLOAD, APK_REQUEST, APK_SEND, READY, EXECUTE, RESULT,

	REQUEST_STATUS, RESPONSE_STATUS,

	BLUETOOTH_PROFILER,

	REGISTER, REGISTERED, OFFLOAD, UNREGISTER, UNREGISTERED, DEVICE_LIST, FREE, CLOUD, CTRL_VM,

	SUPPORT_OFFLOAD,

	PING, PONG,

	NONE,
}
